ErucaCRM.Web/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ErucaCRM.Repository;
using ErucaCRM.Repository.Infrastructure.Contract;
using ErucaCRM.Repository.Infrastructure;
using ErucaCRM.Business.Interfaces;
using ErucaCRM.Web.ViewModels;
using ErucaCRM.Domain;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;
using System.Threading.Tasks;
using ErucaCRM.Utility;
using ErucaCRM.Utility.WebClasses;
using AutoMapper;
using ErucaCRM.Web.Infrastructure;

namespace ErucaCRM.Web.Controllers
{

    [CultureModuleManagement]
    public class SiteController : Controller
    {
        private IUserBusiness userBusiness;
        private IProfileBusiness profileBusiness;
        private ITimeZoneBusiness timeZoneBusiness;
        private ICultureInformationBusiness cultureInformationBusiness;
        private IContentApplicationPageBusiness contentApplicationBusiness;
        public SiteController(IUserBusiness _userBusiness, IProfileBusiness _profileBusiness, ICultureInformationBusiness _cultureInformationBusiness, ITimeZoneBusiness _timeZoneBusiness, IContentApplicationPageBusiness _contentApplicationBusiness)
        {
            userBusiness = _userBusiness;
            profileBusiness = _profileBusiness;
            cultureInformationBusiness = _cultureInformationBusiness;
            timeZoneBusiness = _timeZoneBusiness;
            contentApplicationBusiness = _contentApplicationBusiness;
        }

        public ActionResult Index(string pagename)
        {
            string sitePageName = Constants.PUBLIC_PAGE_HOME;

            LoginModel loginModel = new LoginModel();


            HttpCookie rememberMe = Request.Cookies["RememberMe"];
            if (Request.Cookies["MaxLeadAuditId"] != null)
            {
                Response.Cookies.Remove("MaxLeadAuditId");

            }
            if (rememberMe != null && !string.IsNullOrEmpty(rememberMe.Values["emailId"]) && !string.IsNullOrEmpty(rememberMe.Values["password"]))
            {
                loginModel.EmailId = rememberMe.Values["emailId"];
                loginModel.Password = rememberMe.Values["password"];
                loginModel.isChecked = true;
                UserModel usermodel = userBusiness.ValidateUser(loginModel.EmailId, loginModel.Password, true);
                if (usermodel != null)
                {
                    int userTypeId = IsLogin(loginModel);
                    if (userTypeId == 1)
                    {
                        return RedirectToAction("ContentManagement", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("Home", "User");
                    }
                }
            }
            else if (SessionManagement.LoggedInUser != null && SessionManagement.LoggedInUser.Password != null && SessionManagement.LoggedInUser.Password != null)
            {
                loginModel.EmailId = SessionManagement.LoggedInUser.EmailId;
                loginModel.Password = SessionManagement.LoggedInUser.Password;
                loginModel.isChecked = true;
                UserModel usermodel = userBusiness.ValidateUser(loginModel.EmailId, loginModel.Password, true);
                if (usermodel != null)
                {
                    int userTypeId = IsLogin(loginModel);
                    if (userTypeId == 1)
                    {
                        return RedirectToAction("ContentManagement", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("Home", "User");
                    }
                }

            }
            if (pagename != null)
            {
                sitePageName = pagename;
            }
        

            PublicHomePageVM cultureSpecificSiteContentVM = new PublicHomePageVM();
            CultureSpecificSiteContentModel cultureSpecificSiteContentModel = contentApplicationBusiness.GetPageCultureSpecificContent(sitePageName);
            AutoMapper.Mapper.Map(cultureSpecificSiteContentModel, cultureSpecificSiteContentVM);

            return View(cultureSpecificSiteContentVM);

        }
        [ChildActionOnly]
        public ActionResult RegisterUser(string pagename)
        {
            string sitePageName = Constants.PUBLIC_PAGE_REGISTRATION;


            if (pagename != null)
            {
                sitePageName = pagename;
            }


            RegistrationVM registrationVM = new RegistrationVM();

            ViewBag.success = false;
            ViewBag.CultureList = GetCultureList();
            ViewBag.TimeZoneList = GetTimeZoneList();
            return View(registrationVM);
            //return PartialView("_Registration", registrationVM);
        }
        [HttpGet]
        public ActionResult SetProfile()
        {
         
      
            return View();
        }
        [HttpPost]
        public string SetProfile(string name)
        {
            profileBusiness.UpdateCompanyStandardProfile();

            return "Prolfe Set Success";
        }

        private int IsLogin(LoginModel login)
        {

            UserModel usermodel = userBusiness.ValidateUser(login.EmailId, login.Password, login.isChecked);
            if (usermodel != null)
            {
               
                SessionManagement.LoggedInUser.UserId = usermodel.UserId;
                SessionManagement.LoggedInUser.UserIdEncrypted = usermodel.UserId.Encrypt();
                SessionManagement.LoggedInUser.UserName = (usermodel.FirstName + " " + usermodel.LastName);
                SessionManagement.LoggedInUser.Password = usermodel.Password;
                SessionManagement.LoggedInUser.EmailId = usermodel.EmailId;
                SessionManagement.LoggedInUser.FullName = usermodel.FirstName + " " + usermodel.LastName;
                SessionManagement.LoggedInUser.Role = (Enums.UserType)usermodel.UserTypeId;
                SessionManagement.LoggedInUser.CompanyId = usermodel.CompanyModel.CompanyId;
                SessionManagement.LoggedInUser.CompanyName = usermodel.CompanyModel.CompanyName;
                SessionManagement.LoggedInUser.ProfileImageUrl = usermodel.ImageURL;
                SessionManagement.LoggedInUser.CurrentCulture = usermodel.CultureInformationModel.CultureName;
                SessionManagement.LoggedInUser.TimeZoneOffSet = usermodel.TimeZoneModel.offset;
          
                string pipeSeperatedPermissions = String.Join("|", usermodel.ProfileModel.ProfilePermissionModels.Where(x => x.HasAccess == true).Select(x => x.ModulePermission.Module.ModuleCONSTANT + x.ModulePermission.Permission.PermissionCONSTANT).ToList().ToArray());
                //string pipeSeperatedPermissions = userBusiness.CheckCompanyPlanProfile((int)usermodel.CompanyModel.CompanyId, (int)usermodel.UserId);
                CommonFunctions.SetCookie(SessionManagement.LoggedInUser, pipeSeperatedPermissions, login.isChecked);
            }
            return usermodel.UserTypeId;
        }
        public ActionResult Register(string pagename)
        {
            string sitePageName = Constants.PUBLIC_PAGE_REGISTRATION;

            TempData["View"] = "Register";
            if (pagename != null)
            {
                sitePageName = pagename;
            }
            ViewBag.success = false;
            ViewBag.CultureList = GetCultureList();
            ViewBag.TimeZoneList = GetTimeZoneList();
            RegistrationVM registrationVM = new RegistrationVM();

            CultureSpecificSiteContentModel cultureSpecificSiteContentModel = contentApplicationBusiness.GetPageCultureSpecificContent(sitePageName);

            registrationVM.CultureSpecificPageContent = cultureSpecificSiteContentModel.CultureSpecificPageContent;
            registrationVM.CultureSpecificPageMetaTitle = cultureSpecificSiteContentModel.CultureSpecificPageMetaTitle;
            registrationVM.CultureSpecificPageMetaTags = cultureSpecificSiteContentModel.CultureSpecificPageMetaTags;

            return View(registrationVM);

        }
        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            if (ModelState.IsValid)
            {
                UserModel usermodel = userBusiness.ValidateUser(login.EmailId, login.Password, login.isChecked);
                if (usermodel != null)
                {
                    int userTypeId = IsLogin(login);
                    if (userTypeId == 1)
                    {
                        return RedirectToAction("ContentManagement", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("Home", "User");
                    }
                }
                else
                {
                    ModelState.AddModelError("EmailId", CommonFunctions.GetGlobalizedLabel("Login", "LoginErrorMessage"));
                    //Rebind model for displaying  Content

                    login = new LoginModel();

                    string sitePageName = Constants.PUBLIC_PAGE_LOGIN;

                    CultureSpecificSiteContentModel cultureSpecificSiteContentModel = contentApplicationBusiness.GetPageCultureSpecificContent(sitePageName);

                    login.CultureSpecificPageContent = cultureSpecificSiteContentModel.CultureSpecificPageContent;
                    login.CultureSpecificPageMetaTitle = cultureSpecificSiteContentModel.CultureSpecificPageMetaTitle;
                    login.CultureSpecificPageMetaTags = cultureSpecificSiteContentModel.CultureSpecificPageMetaTags;
                    ViewBag.CultureList = GetCultureList();
                    ViewBag.TimeZoneList = GetTimeZoneList();
                    return View(login);
                }
            }
            else
            {
                login = new LoginModel();

ErucaCRM.Web/Views/Site/AboutUs.cshtml
@model ErucaCRM.Web.ViewModels.PublicAboutUsPageVM
@using ErucaCRM.Web.Infrastructure;
@using ErucaCRM.Utility;

@{
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/ecmascript">

    $(document).ready(function () {
        $('._question').click(function () {

            $(this).next().toggle('fast');
        })
    })
</script>
<div class="cultureContentblock">
    <div class="cultureContent">

        @Html.Raw(string.IsNullOrWhiteSpace(Model.CultureSpecificPageContent) ? "" : Model.CultureSpecificPageContent.Replace("&nbsp;", " "))
    </div>
</div>

ErucaCRM.Web/Views/Site/ContactUs.cshtml
@model ErucaCRM.Web.ViewModels.CultureSpecificSiteContentVM

@{
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="body-wrapper">
    <div class="contact-pages">
        <div class="contact-page-left">
            <h1>Contact Us</h1>
            <p class="para-graph">Sales Enquiries</p>
            <p class="email">Email : <span><a href="javascript:void(0)">sales@erucatech.com</a></span></p>
            <p class="para-graph">Phone :</p>
            <p class="addresh">US : <span><a href="javascript:void(0)">+1 888-888-8888</a></span></p>
            <p class="addresh">US : <span><a href="javascript:void(0)">+45 (25) 1 888-888-8888</a></span></p>
            <p class="addresh">US : <span><a href="javascript:void(0)">+1 888-888-8888</a></span></p>
            <p class="addresh">Chandigarh : <span><a href="javascript:void(0)">+1 888-888-8888</a></span></p>
        </div>
        <div class="contact-page-right">
            <div class="map">
                <img src="content//Content/images/map.png" alt="" title="" class="img"></div>
            <a href="javascript:void(0)" class="zoom-aro">
                <img src="/Content/images/map-zoom.png" alt="" title="zoom"></a>
        </div>
        <div class="clear"></div>
    </div>
</div>

@*  <div class="cultureContentblock">
            <div class="cultureContent">
                @Html.Raw(string.IsNullOrWhiteSpace(Model.CultureSpecificPageContent) ? "" : Model.CultureSpecificPageContent.Replace("&nbsp;", " "))
            </div>
        </div>
   *@

ErucaCRM.Web/Views/Site/Feature.cshtml
@model ErucaCRM.Web.ViewModels.PublicFeaturePageVM
@using ErucaCRM.Web.Infrastructure;
@using ErucaCRM.Utility;



@{
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="cultureContentblock">
    <div class="cultureContent">

        @Html.Raw(string.IsNullOrWhiteSpace(Model.CultureSpecificPageContent) ? "" : Model.CultureSpecificPageContent.Replace("&nbsp;", " "))
    </div>
</div>

ErucaCRM.Web/Views/Site/ForgotPassword.cshtml
@using ErucaCRM.Web.Infrastructure;

@model ErucaCRM.Web.ViewModels.ForgotPasswordVM

@{
    //ViewBag.Title = "Recover Your Password";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
}
@section scripts {
    <script src="@Url.Content("~/Scripts/ErucaCRM.Site/ErucaCRM.Site.ForgotPassword.js")" type="text/javascript"></script>
}

@section ReadyScripts
{
ErucaCRM.Site.ForgotPassword.pageLoad();
}

<style>
    .msgssuccess { color: green !important; }

    .msgerror { color: red !important; }
</style>
<div class="body-wrapper forgotpassword">


    <h2 class="header-forgotpassword">@Html.CultureSpecificDisplay(model => model.PageHeaders.PageHeaderRecoverYourPassword)</h2>
    <p>@Html.ValidationMessageFor(model => model.EmailId)</p>
    <div style="height: 20px">
        <p class="forgotpassword-error"></p>
    </div>
    <div class="recover-password">
        @Html.TextBoxFor(model => model.EmailId, new { @class = "input-text", placeholder = @Html.CultureSpecificDisplay(model => model.PageLabels.Email) })
        @*    <input class="input-text" placeholder = "@Html.CultureSpecificDisplay(model => model.PageLabels.Email)" id="EmailId"/>*@
        <p>
            <input id="RecoverPassword" type="submit" class="button buttonforgotpassword" value="@Html.CultureSpecificDisplay(model => model.PageButtons.ButtonRecoverForgotPassword)" />
        </p>
    </div>




</div>

ErucaCRM.Web/Views/Site/Login.cshtml
@using ErucaCRM.Utility;
@using ErucaCRM.Web.Infrastructure;
@using ErucaCRM.Web.ViewModels;
@model ErucaCRM.Web.ViewModels.LoginModel
@{
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
}

<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
@*    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/main.css")" />*@

<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/OuterLayoutCss.css")" />

<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
<link href="@Url.Content("~/Content/css/font-awesome/css/font-awesome.css")" rel="stylesheet" />
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/knockout-3.0.0.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/ErucaCRM.Framework/ErucaCRM.Framework.Core.js")"></script>
<script type="text/javascript" src="~/Scripts/ErucaCRM.Messages/@CommonFunctions.GetCurrentCulturScript()?t=@DateTime.Today.Ticks"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="back-bg">
        <div class="main-div">
            <div class="login">
                <div class="left-login">
                    <a href="@Url.Content("/Home")">
                        <img src="/content/images/@CommonFunctions.GetCurrentCulturLoginLogo()" alt="" title="logo"></a>
                </div>
                <div class="clear"></div>
                <div class="right-login">
                    <div class="login-form">
                        <p class="sign">
                            <h1>@Html.CultureSpecificDisplay(model => model.PageSubHeaders.PageSubHeaderLoginInfo)</h1>
                        </p>
                        <br />

                        <div class="login-validation-span">@Html.ValidationMessageFor(m => m.EmailId)</div>
                        <div class="input-box">
                            <a href="javascript:void(0)" class="background-img">
                                <img src="/content/images/man.png" alt="" title=""></a>@Html.TextBoxFor(m => m.EmailId, new { placeholder = Html.CultureSpecificDisplay(model => model.PageLabels.UserName), @tabindex = 1 })
                        </div>
                        <div class="login-validation-span">@Html.ValidationMessageFor(m => m.Password)</div>
                        <div class="input-box">
                            <a href="javascript:void(0)" class="background-img">
                                <img src="/content/images/kye.png" alt="" title=""></a>@Html.TextBoxFor(m => m.Password, new { type = "password", placeholder = Html.CultureSpecificDisplay(model => model.PageLabels.Password), @tabindex = 2 })
                        </div>
                        <span class="checkrember">
                            @*  <input type="checkbox" value="" tabindex="3">*@
                            @Html.CheckBoxFor(m => m.isChecked)
                            &nbsp; @Html.CultureSpecificDisplay(model => model.PageLabels.KeepMeSingnedIn)</span><br />
                        <br />
                        <br />
                        <a href="javascript:void(0)">
                            <input type="submit" class="button" tabindex="4" value="@Html.CultureSpecificDisplay(model => model.PageButtons.ButtonSignIn)"></a><br />
                        <br />
                        <br />
                        <p class="log">
                        </p>

                    </div>
                </div>

            </div>
        </div>
        <div class="forword">
            @* <span class="account"><a href="javascript:void(0)">Create an account</a></span>
            <span class="account1"><a href="javascript:void(0)">Forword password</a></span>*@
            <span class="account"><a href="@Url.Content("/Register")" class="_register hyperlink register">@Html.CultureSpecificDisplay(model => model.PageButtons.LinkButtonSignUpNow)&nbsp;|</a></span>
            <span class="password account1">@Html.ActionLink(@Html.CultureSpecificDisplay(model => model.PageButtons.LinkButtonForgotPassword), "ForgotPassword", "Site", null, new { @class = "hyperlink" })</span>
        </div>
    </div>
}

ErucaCRM.Web/Views/Site/MobileCRM.cshtml
@model ErucaCRM.Web.ViewModels.PublicMobileCRMPageVM 
@using ErucaCRM.Web.Infrastructure;
@using ErucaCRM.Utility;

@{  
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "ErucaCRM Mobile Apps for Managers and Sales team";
}
<div class="cultureContentblock">
    <div class="cultureContent">

        @Html.Raw(string.IsNullOrWhiteSpace(Model.CultureSpecificPageContent) ? "" : Model.CultureSpecificPageContent.Replace("&nbsp;", " "))
    </div>
</div>

ErucaCRM.Web/Views/Site/Register.cshtml
@using Recaptcha.Web.Mvc;
@using ErucaCRM.Utility;
@using ErucaCRM.Web.Infrastructure;


@model ErucaCRM.Web.ViewModels.RegistrationVM

@{
    ViewBag.Title = Model.CultureSpecificPageMetaTitle;
    ViewBag.MetaTag = Model.CultureSpecificPageMetaTags;
    //  Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/css/OuterLayoutCss.css")" />

<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
<link href="@Url.Content("~/Content/css/font-awesome/css/font-awesome.css")" rel="stylesheet" />


<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.10.2.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/knockout-3.0.0.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/ErucaCRM.Framework/ErucaCRM.Framework.Core.js")"></script>
<script type="text/javascript" src="~/Scripts/ErucaCRM.Messages/@CommonFunctions.GetCurrentCulturScript()?t=@DateTime.Today.Ticks"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script>
    $(document).ready(function () {
        ErucaCRM.User.AddUser.pageLoad();
        $('#FirstName').focus();
    })



</script>

<script src="@Url.Content("~/Scripts/ErucaCRM.User/ErucaCRM.User.AddUser.js")" type="text/javascript"></script>
@section scripts {
    @* @Scripts.Render("~/bundles/RegisterScripts") *@
}


@if (ViewBag.success == true)
{
    <div class="message-success">

        @Html.Raw(Convert.ToString(ViewBag.RegistrationSuccessWelComeMessage))

    </div>
    <script>
        setTimeout("window.location.href='/User/Home';", 6000)
    </script>
}

@*<p class="error">
    @Html.ValidationSummary(true)
</p>*@

@*<div class="body-wrapper">*@
@using (Html.BeginForm("Register", "Site"))
{
    @Html.AntiForgeryToken()
 
    <div class="back-bg-register">
        <div class="main-div">
            <div class="left-Register">
                <a href="@Url.Content("/home")">
                    <img src="/content/images/@CommonFunctions.GetCurrentCulturLoginLogo()" alt="" title="logo"></a>
            </div>
            <div class="LogIn1">
                <p>@Html.CultureSpecificDisplay(model => model.PageHeaderCreate, "Registration")</p>
                @if (ViewBag.success == false)
                {
                    <div class="registration-error">
                        @Html.ValidationSummary(true)
                        @Html.Raw(ViewBag.StatusMessage)
                    </div>
                    <br />
                }
                @Html.ValidationMessageFor(m => m.FirstName)
                <div class="input-box1">
                    <img src="/content/images/frist-name.png" class="background-img">
                    @Html.TextBoxFor(m => m.FirstName, new { maxlength = 50, @class = "input-text-Registration registerTxtbox", placeholder = @Html.CultureSpecificDisplay(m => m.FirstName) })
                    <div class="clear"></div>
                </div>
                @Html.ValidationMessageFor(m => m.LastName)
                <div class="input-box1">
                    <img src="/content/images/frist-name.png" class="background-img">

                    @Html.TextBoxFor(m => m.LastName, new { maxlength = 50, @class = "input-text-Registration registerTxtbox", placeholder = @Html.CultureSpecificDisplay(m => m.LastName) })
                    <div class="clear"></div>
                </div>
                @Html.ValidationMessageFor(m => m.Company.CompanyName)
                <div class="input-box1">
                    <img src="/content/images/company-name.png" class="background-img">
                    @Html.TextBoxFor(m => m.Company.CompanyName, new { maxlength = 50, @class = "input-text-Registration registerTxtbox", placeholder = @Html.CultureSpecificDisplay(m => m.Company.CompanyName) })
                    <div class="clear"></div>
                </div>
                @Html.ValidationMessageFor(m => m.EmailId)
                <div class="input-box1">
                    <img src="/content/images/email-id.png" class="background-img">
                    @Html.TextBoxFor(m => m.EmailId, new { maxlength = 50, @class = "input-text-Registration registerTxtbox", @autocomplete = "off", placeholder = @Html.CultureSpecificDisplay(m => m.EmailId) })
                    <div class="clear"></div>
                </div>
                @Html.ValidationMessageFor(m => m.Password)
                <div class="input-box1">
                    <img src="/content/images/password.png" class="background-img">
                    @Html.PasswordFor(m => m.Password, new { maxlength = 50, minlength = 6, @class = "input-text-Registration registerTxtbox", @autocomplete = "off", placeholder = @Html.CultureSpecificDisplay(m => m.Password) })
                    <div class="clear"></div>
                </div>
                @Html.ValidationMessageFor(m => m.ConfirmPassword)
                <div class="input-box1">
                    <img src="/content/images/password.png" class="background-img">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { maxlength = 50, @class = "input-text-Registration registerTxtbox", @autocomplete = "off", placeholder = @Html.CultureSpecificDisplay(m => m.ConfirmPassword) })
                    <div class="clear"></div>
                </div>
                <div class=" registration-error"></div>
                @(Html.DropDownListFor(model => model.CultureInformationId, new SelectList(ViewBag.CultureList, "CultureInformationId", "CultureDescription", 0), new { @class = "dropdown" }))
                @(Html.DropDownListFor(model => model.TimeZoneId, new SelectList(ViewBag.TimeZoneList, "TimeZoneId", "TimeZoneDescription", 0), new { @class = "dropdown" }))
                <div class="display-field-registration registration-captcha">@Html.Recaptcha(theme: Recaptcha.Web.RecaptchaTheme.Red)</div>
                <div class="display-label-registration">&nbsp;</div>
                <div class="display-field-registration">
                    <input type="submit" id="register" value=" @Html.CultureSpecificDisplay(model => model.PageButtons.ButtonRegister, "Registration")" class="register-left-registration-button _one-click-submit-button" />

                    @Html.ActionLink(@Html.CultureSpecificDisplay(model => model.PageButtons.LinkButtonAlreadyHaveAnAccount, "Registration"), "Login", "Site", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "account" })
                </div>
            </div>

            <div class="clear"></div>

        </div>
    </div>
}

ErucaCRM.Web/Views/Site/SetProfile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SetProfile</title>
</head>
<body>
    <div>
         @using(Html.BeginForm())
        {
        <input type="submit" value="Update Company Standard Profile" />
        }
    </div>
</body>
</html>